#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countApplesAndOranges' function below.
#
# The function accepts following parameters:
#  1. INTEGER s
#  2. INTEGER t
#  3. INTEGER a
#  4. INTEGER b
#  5. INTEGER_ARRAY apples
#  6. INTEGER_ARRAY oranges
#

def countApplesAndOranges(s, t, a, b, apples, oranges):
    #range -> 7 - 11
    #apple location(a) -> 5 and thrown apple -> -2 2 1
    # orange location(b) -> 15 and thrown orange -> 5 -6
    c_apple,c_orange = 0,0
    for apple in apples:
        if a + apple >= s and a+apple <= t:
            c_apple +=1
    for orange in oranges:
        if b+ orange >=s and b+ orange <=t:
            c_orange+=1
    print(c_apple)
    print(c_orange)
        
if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    s = int(first_multiple_input[0])

    t = int(first_multiple_input[1])

    second_multiple_input = input().rstrip().split()

    a = int(second_multiple_input[0])

    b = int(second_multiple_input[1])

    third_multiple_input = input().rstrip().split()

    m = int(third_multiple_input[0])

    n = int(third_multiple_input[1])

    apples = list(map(int, input().rstrip().split()))


    """
2 3
1 5
1 1
-2
-1

0
0
"""

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
