#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    # mn = min(arr)
    # mx = max(arr)
    arr.sort()
    mn_sum,mx_sum = 0,0
    for i in arr[:len(arr)-1]:
        mn_sum+=i
    for i in arr[1:]:
        mx_sum+=i
    print(mn_sum,mx_sum)

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
 
