#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'utopianTree' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#

def odd(n):
    return ((n % 2) == 1);

def even(n):
    return ((n % 2) == 0);

def utopianTree(n):
    if n == 0:
        return 1;
    elif odd(n):
        return 2 * utopianTree(n-1);
    elif even(n):
        return 1 + utopianTree(n-1);

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        result = utopianTree(n)

        fptr.write(str(result) + '\n')

    fptr.close()
